### ISSUE TITLE
'check_resource_methods_by_displayname crashes' when raml file item has more than two levels

### ISSUE THREAD

**Issue by NickNYU** [vmware/nsxramlclient#18]
The part of raml file(which cause this issue) is as below:
```
/2.0/universalsync:
  displayName: universalSync
  description: Configuring Universal Sync for the NSX manager
  /configuration:
    /role:
      displayName: universalSyncConfigurationRole
      description: Universal Sync Configuration
      post:
        displayName: universalSyncConfigurationRoleSet
        description: Set the Universal Sync Configuration role
        queryParameters:
          action:
            displayName: action
            description: |
              Set the role of the NSX manager. Possible values are
              set-as-standalone, set-as-primary, set-as-secondary
      get:
        displayName: universalSyncConfigurationRoleRead
        description: Get the Universal Sync Configuration role
```

The part of code which cause this issue is as:
```
    def _get_resource_url_data(self, resource, res_url_data=None):
        # this method runs through the base raml file backwards recursively to construct the
        # url of the resource and collect all uri parameters back to the root
        if not res_url_data:
            res_url_data = {'constructed_url': '', 'uri_parameters': {}, 'query_parameters': {}}
        if resource[1].parentResource:
            try:
                resource[1].parentResource.displayName
            except:
                raise Exception('The parent resource of {} is missing a display '
                                'name in the RAMl File'.format(resource[0]))
```

resource[1].parentResource.displayName is not as expected in the raml file, as I print out the result of  resource[1].parentResource

```
{
	'displayName': None,
	'methods': None,
	'description': None,
	'uriParameters': None,
	'is_': None,
	'baseUriParameters': None,
	'type': None,
	'resources': OrderedDict([('/role', {
				'displayName': 'universalSyncConfigurationRole',
				'methods': OrderedDict([('get', {
							'body': None,
							'description': 'Get the Universal Sync Configuration role',
							'queryParameters': None,
							'headers': None,
							'notNull': None,
							'baseUriParameters': None,
							'protocols': None,
							'responses': None
						}), ('post', {
							'body': None,
							'description': 'Set the Universal Sync Configuration role',
							'queryParameters': OrderedDict([('action', {
										'repeat': None,
										'displayName': 'action',
										'name': None,
										'default': None,
										'pattern': None,
										'enum': None,
										'maximum': None,
										'required': None,
										'minimum': None,
										'minLength': None,
										'maxLength': None,
										'type': 'string',
										'example': None,
										'description': 'Set the role of the NSX manager. Possible values are\nset-as-standalone, set-as-primary, set-as-secondary\n'
									})]),
							'headers': None,
							'notNull': None,
							'baseUriParameters': None,
							'protocols': None,
							'responses': None
						})]),
				'description': 'Universal Sync Configuration',
...etc
``` 

To address this issue, either we modify the raml file adding displayName to the 'config' layer.
Or, we could modify the logic of the code
